### ISSUE TITLE
Create GitIgnore

### ISSUE THREAD

**Issue by morganog** [morganog/CookNook#4]
Create GitIgnore folder and make env (the virtual environment) ignored. 

- Less Cluttered
- Better Experience for Dev User

- [ ] GitIgnore Env Folder

**Comment by morganog** [comment]
I removed hacktober label to this issue due to it not being meaningful enough Code to contribute. If you think this is wrong or does not violate participation rules, feel free to reach out to me and we can discuss/change it. Thank you.

**Comment by abshek7** [comment]
I would like to work on this issue 
Can you please assign the issue to me?

**Comment by morganog** [comment]
> I would like to work on this issue 
> 
> Can you please assign the issue to me?

Yes! You are free to work on this issue, as well as the other issue you commented on. I think it has yet to been forked.
